name: Build for ARM64 Linux

on:
  push:
    branches: [ "main" ]  # 触发分支（按需修改）
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 的 Linux 环境

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'  # 按需修改 Go 版本

    - name: Build for ARM64 Linux
      env:
        GOOS: linux    # 目标操作系统
        GOARCH: arm64  # 目标架构
        CGO_ENABLED: 1  # 禁用 CGO（除非需要 C 依赖）
      run: |
        go build -v -o main-arm64 ./main.go

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: sqlite_cmd-arm64
        path: sqlite_cmd-arm64
