name: Build for ARM64 Linux

on:
  push:
    branches: [ "main" ]  # 触发分支（按需修改）
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 的 Linux 环境

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install ARM64 Cross-Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu  # 安装交叉编译工具链

    - name: Install NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        echo "NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r25b" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'  # 按需修改 Go 版本

    - name: Build
      env:
        GOOS: android
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: aarch64-linux-android33-clang
      run: go build -ldflags "-extldflags=-pie" -o main-arm64 ./main.go
        
    - name: Debug List Files
      run: ls -la  # 查看当前目录内容，确认文件存在
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: main-arm64
        path: ./
